In [81]:
import pandas as pd
import numpy as np

In [36]:
df=pd.read_csv("IMDB Dataset.csv")

In [37]:
df.head()
# df.shape

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [38]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [39]:
# Removing Duplicates

df.drop_duplicates(inplace=True)

In [40]:
df.shape #Duplicates removed

(49582, 2)

## Text Pre-processing

#### 1.Converting to lowercase

In [41]:
df["review"]=df["review"].str.lower()

In [42]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

#### 2.Removing the URL's

In [43]:
import re

In [44]:
def remove_urls(text): # \S -> non white space characters \s -> white space character
    return re.sub(r"http\S+","", text) #(pattern, replacement, string to perform on) eg - http://www.google.com

In [45]:
df["review"]=df["review"].apply(remove_urls)

#### 3.Removing HTML Tags

In [46]:
def remove_HTML_Tags(text):
    return re.sub(r"<.*?>","", text) # . -> remove any character since <> along with the <>
                                    # * -> remove any number or characters and words 0 ore more

In [47]:
df["review"]=df["review"].apply(remove_HTML_Tags)

In [48]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [49]:
print(repr(df["review"].iloc[0]))

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

#### 4.Removing Punctuations

In [50]:
# A-Z , a-z, 0-9 and spaces i.e \s -> apart from these ascii values remove all the others
def remove_punctuations(text):
    return re.sub(r"[^A-Za-z0-9\s]","", text)

In [51]:
df["review"]=df["review"].apply(remove_punctuations)

In [52]:
print(repr(df["review"].iloc[0]))

'one of the other reviewers has mentioned that after watching just 1 oz episode youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordit is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awayi would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare forget pretty pictures painted for mainstream audiences forget charm forget romanceoz doesnt mess around the first episode i ever saw struck me as so nasty it was surreal i couldnt say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience watching oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side'

#### 5.Removing Stop Words

In [30]:
import nltk # Natural Language ToolKit

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sanbi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\sanbi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sanbi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [53]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [54]:
def remove_stopwords(text):
    tokens=word_tokenize(text)
    stop_words=stopwords.words("english")

    filtered_tokens = []

    for word in tokens:
        if word.lower() not in stop_words:
            filtered_tokens.append(word)

    return " ".join(filtered_tokens)

In [55]:
df["review"]=df["review"].apply(remove_stopwords)

In [56]:
print(repr(df["review"].iloc[0]))

'one reviewers mentioned watching 1 oz episode youll hooked right exactly happened methe first thing struck oz brutality unflinching scenes violence set right word go trust show faint hearted timid show pulls punches regards drugs sex violence hardcore classic use wordit called oz nickname given oswald maximum security state penitentary focuses mainly emerald city experimental section prison cells glass fronts face inwards privacy high agenda em city home manyaryans muslims gangstas latinos christians italians irish moreso scuffles death stares dodgy dealings shady agreements never far awayi would say main appeal show due fact goes shows wouldnt dare forget pretty pictures painted mainstream audiences forget charm forget romanceoz doesnt mess around first episode ever saw struck nasty surreal couldnt say ready watched developed taste oz got accustomed high levels graphic violence violence injustice crooked guards wholl sold nickel inmates wholl kill order get away well mannered middle class inmates turned prison bitches due lack street skills prison experience watching oz may become comfortable uncomfortable viewingthats get touch darker side'

#### 6.Stemming

In [57]:
# running->Run i.e bringing the words to their base form
# played->play
# To achieve this, we use a method called PorterStemming

from nltk.stem import PorterStemmer

In [59]:
def stemming(text):
    ps=PorterStemmer()
    stemmed_words=[]
    tokens=word_tokenize(text)

    for word in tokens:
        stemmed_word=(ps.stem(word))
        stemmed_words.append(stemmed_word)
    return " ".join(stemmed_words)

In [60]:
df["review"]=df["review"].apply(stemming)

In [61]:
print(repr(df["review"].iloc[0]))

'one review mention watch 1 oz episod youll hook right exactli happen meth first thing struck oz brutal unflinch scene violenc set right word go trust show faint heart timid show pull punch regard drug sex violenc hardcor classic use wordit call oz nicknam given oswald maximum secur state penitentari focus mainli emerald citi experiment section prison cell glass front face inward privaci high agenda em citi home manyaryan muslim gangsta latino christian italian irish moreso scuffl death stare dodgi deal shadi agreement never far awayi would say main appeal show due fact goe show wouldnt dare forget pretti pictur paint mainstream audienc forget charm forget romanceoz doesnt mess around first episod ever saw struck nasti surreal couldnt say readi watch develop tast oz got accustom high level graphic violenc violenc injustic crook guard wholl sold nickel inmat wholl kill order get away well manner middl class inmat turn prison bitch due lack street skill prison experi watch oz may becom comfort uncomfort viewingthat get touch darker side'

#### 7.Encoding

In [85]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df["sentiment"]=le.fit_transform(df["sentiment"])

In [86]:
y=df["sentiment"]

y.head()

0    1
1    1
2    1
3    0
4    1
Name: sentiment, dtype: int64

#### 8.Vectorization

In [87]:
df.head()

                                              review  sentiment
0  one review mention watch 1 oz episod youll hoo...          1
1  wonder littl product film techniqu unassum old...          1
2  thought wonder way spend time hot summer weeke...          1
3  basic there famili littl boy jake think there ...          0
4  petter mattei love time money visual stun film...          1

In [88]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [89]:
tf=TfidfVectorizer(max_features=5000)

X=tf.fit_transform(df["review"])

In [90]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4048128 stored elements and shape (49582, 5000)>

## TensorDatasets and DataLoaders

In [91]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [93]:
X_train.shape

(39665, 5000)

In [94]:
X_test.shape

(9917, 5000)

In [95]:
# Converting X_train and X_test from Sparse Matrix to Numpy array to pass it to Dataset and DataLoaders
X_train=X_train.toarray()
X_test=X_test.toarray()
X_train

array([[0.23842592, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(39665, 5000))

In [97]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [99]:
train_set=TensorDataset(
    torch.from_numpy(X_train).float(), # converting to tensors first inside this only and then creating the
                                       # TensorDataset
    torch.from_numpy(y_train.to_numpy(copy=True)).float()  #Since y_train and y_test is a DataFrame
)

test_set=TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.to_numpy(copy=True)).float()
)

In [100]:
train_loader=DataLoader(train_set, shuffle=True, batch_size=64)
test_loader=DataLoader(test_set, shuffle=True, batch_size=64)

## Defining our RNN Model

In [109]:
import torch.nn as nn
import torch.optim as optim

In [110]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super().__init__()

        self.hidden_size=hidden_size
        self.num_layers=num_layers

        # RNN Layer
        self.rnn=nn.RNN(input_size, hidden_size, num_layers, batch_first=True)

        # Fully Connected Layer
        self.fc=nn.Linear(hidden_size, 1)

    def forward(self, x):
        #Initializing the hidden state which is completely optional
        #shape (num of layers, batch size, hidden size)
        h0=torch.zeros(self.num_layers, x.size(0), self.hidden_size)


        out, _=self.rnn(x,h0)
        # 1st Value= hidden state of all the timesteps =>shape (batch, seq_len, hidden size)
        # 2nd Value= hidden state of the last timestep

        out=self.fc(out[:, -1, :]) #getting the last timestep\

        return out

## Building our RNN Model

In [111]:


input_size=X_train.shape[1]  # shape(40000,5000) => takes 5000 from this and assigns to input_size
model=RNN(input_size)

# loss, Optimizer
criterion=nn.BCELoss() #BinaryCrossEntropy Loss
optimizer=optim.Adam(model.parameters())

## Training our Model

In [114]:
epochs=10

for epoch in range(epochs):
    model.train()
    
    for Xb,yb in train_loader:
        #Xb= Features of 1 batch, yb= Outputs/Labels of 1 batch
        optimizer.zero_grad()

        Xb=Xb.unsqueeze(1) #converting tf-idf vectors that are matrices of 2x2 to 3x3 (adding extra dimension)
                        # since the model below expects a 3 Dimensional input, so we add a singleton direction
        outputs=model(Xb) # (batch size, 1)

        #Converting the raw linear combination logit the out returns into probabality values
        outputs=torch.sigmoid(outputs.squeeze()) # removes a dimension/singleton direction since sigmoid expects it, so=> (batch size,)
        
        loss=criterion(outputs, yb)  #Loss Computation
        loss.backward() #Back Propagation
        optimizer.step() #Updating the parameters

    print(f"Epoch={epoch+1}/{epochs} ==> Loss: {loss.item()}")

Epoch=1/10 ==> Loss: 0.20515692234039307
Epoch=2/10 ==> Loss: 0.26682591438293457
Epoch=3/10 ==> Loss: 0.1562444567680359
Epoch=4/10 ==> Loss: 0.3546963930130005
Epoch=5/10 ==> Loss: 0.10304445028305054
Epoch=6/10 ==> Loss: 0.21133160591125488
Epoch=7/10 ==> Loss: 0.272992342710495
Epoch=8/10 ==> Loss: 0.25587570667266846
Epoch=9/10 ==> Loss: 0.3229829967021942
Epoch=10/10 ==> Loss: 0.37165307998657227

## Evaluating or Testing our RNN Model

In [116]:
# Evaluating or Testing our CNN Model

model.eval()

correct_labels=0
total_labels=0

with torch.no_grad():

    for Xb,yb in test_loader:
        Xb=Xb.unsqueeze(1) #converting to 3x3 
        
        outputs=model(Xb) # model.forward(Xb) works too but not recommendeded

        #Converting the raw linear combination logit the out returns into probabality values        
        predicted=(torch.sigmoid(outputs.squeeze())>0.5).float()# removes a dimension/singleton direction since sigmoid expects it, so=> (batch size,)
   
        correct_labels+=(predicted==yb).sum().item() #for one batch
        total_labels+=yb.size(0) #actual number of samples in each batch

print("Total Values:", total_labels)
print("Correct Values:", correct_labels)
print("Accuracy Score:",(correct_labels/total_labels)*100)

Total Values: 9917
Correct Values: 8633
Accuracy Score: 87.05253604920843